# ============================================================
# bff-web: canal Web
# ============================================================

server.port=8091

# --- Integracion con ms-cuentas via Service Discovery ---
# Ya no hay URL fija: se resuelve por nombre logico en Eureka.
ms-cuentas.service-id=bancoxyz-ms-cuentas
ms-cuentas.timeout.conexion-ms=3000
ms-cuentas.timeout.lectura-ms=5000

# --- Credenciales con las que este BFF se autentica ante ms-cuentas ---
ms-cuentas.credenciales.usuario=svc-cuentas
ms-cuentas.credenciales.clave=Cuentas-2026

# --- Tolerancia a fallos (Resilience4j) ---
resilience4j.circuitbreaker.instances.msCuentas.register-health-indicator=true
resilience4j.circuitbreaker.instances.msCuentas.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.msCuentas.sliding-window-size=10
resilience4j.circuitbreaker.instances.msCuentas.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.msCuentas.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.msCuentas.wait-duration-in-open-state=15s
resilience4j.circuitbreaker.instances.msCuentas.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.msCuentas.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.msCuentas.ignore-exceptions[0]=cl.duoc.bancoxyz.bff.web.exceptions.CuentaNoEncontradaException
resilience4j.circuitbreaker.instances.msCuentas.ignore-exceptions[1]=cl.duoc.bancoxyz.bff.web.exceptions.SolicitudRechazadaException


# --- Seguridad (HTTP Basic + roles) ---
seguridad.canal.usuario=canal-web
seguridad.canal.clave=Web-2026
seguridad.invitado.usuario=invitado-web
seguridad.invitado.clave=Invitado-2026

logging.level.cl.duoc.bancoxyz.bff=DEBUG
logging.level.io.github.resilience4j=DEBUG

# --- HTTPS desactivado en la semana 6 (ver DOCUMENTACION_TECNICA.txt, seccion 6) ---
#server.ssl.enabled=true
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=BancoXYZ-Web-2025
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=bff-web
