# Backend Git: los archivos de configuracion viven en un repositorio aparte.
# Crear el repositorio y subir el contenido de la carpeta config-repo.
spring.cloud.config.server.git.uri=https://github.com/KakoGF/bancoxyz-config-repo
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.timeout=10
